### ISSUE TITLE
Add ability to rename notebooks and notes

### ISSUE THREAD

**Issue by n1try** [n1try/mininote#1]

**Comment by SioJL13** [comment]
I would like to check this one out.

**Comment by twopeas** [comment]
Very new to Vue, but I'd like to take a stab at this!

**Comment by anurag-rai** [comment]
Hey, I'd like to work on this issue, if no-one else is working on it.

Any thoughts on what it should look like at the user end? Should there be an option to change the notebook name in the settings? Or another button near a notebook/note

**Comment by n1try** [comment]
My suggestion would be to have the ability to

- change a notebook's name in the settings dialog
- change a note's name via a dialog that is triggered through a button similar to the trash icon

But if you guys have better ideas, let me know!

**Comment by anurag-rai** [comment]
I have implemented the renaming notebook part of it. I have a few thoughts on how the APIs are implemented. They are not very RESTFUL currently. Anyhow, please do check the renaming part of it. 

Also fixed a bug in the code where the user updates a password but then cannot update password again as the Vue password state is stale.

An extension issue with this the clear the modal text area when the settings modal is complete.

Currently implementing the renaming notes part.

**Comment by n1try** [comment]
Alright, just let me know when you're finished and have pushed everything.
