### ISSUE TITLE
Running dev env on frontend with Node backend

### ISSUE THREAD

**Issue by VinayakBagaria** [n1try/mininote#10]
Can you describe how to run the frontend part of it on Vue's dev server, and interact with the node backend? I want to edit the code and see the live changes.

**Comment by n1try** [comment]
I haven't tried it but my guess is that you would have to do the following:
- Start backend with `debug` flag (see `config.js`)
- Edit `mininote-frontend/src/services/NotesApiService.js` and set the `apiBaseUrl` to the absolute URL where your backend is listening, e.g. `http://localhost:8080/api/`
- Run `vue serve` in frontend directory

**Comment by n1try** [comment]
* `NODE_ENV=dev npm start`
* `cd mininote-frontend`
* Edit `services/NotesApiService.js` and temporarily change `apiBaseUrl` to `http://localhost:3000/api`
* `npm run dev`
