### ISSUE TITLE
API endpoints for single notes instead of entire notebooks

### ISSUE THREAD

**Issue by n1try** [n1try/mininote#14]
... in order to save bandwidth.

**Comment by IamRaviTejaG** [comment]
@n1try I'd like to work on this, can you please elaborate a bit on this issue?!

**Comment by n1try** [comment]
Yes, sure.

A notebook consists of several notes and each note is basically a chunk of Markdown text. When you hit the save button, the entire notebook, including ALL notes is serialized to JSON and sent to `/api/notebook/:id/notes` via a PUT. This is inefficient, since large parts of the data transferred over the network is unchanged. 

It would be more convenient to be able to PUT to `/api/notebook/:id/notes/:noteId` only the specific note that had currently been modified. This includes a new endpoint as well as adaptions in the frontend.

Also don't forget to implement some kind of "dirty checking", meaning that there should be a warning modal dialog (_You have unsaved changes. Do you want to discard them?_) when the user has made changes to a specific note, has not saved them yet, but wants to switch to another note.

**Comment by IamRaviTejaG** [comment]
@n1try Well, having worked with only NodeJS before, I'd like to mention that I can definitely help create the endpoint with specifically the `:noteid` parameter. But I cannot make relevant changes to the frontend, because I haven't worked on it before.

So is it fine if I just publish a PR just making the relevant changes to the API backend?

**Comment by n1try** [comment]
To be honest, I don't think it makes sense to split this issue.

**Comment by IamRaviTejaG** [comment]
@n1try In that case, I'll try to read through the Vue.JS docs and try fixing things up on the frontend too. 😄

**Comment by sk9331657** [comment]
@n1try  Can I work on it ?? I can fix both backend and frontend.
