### ISSUE TITLE
Why is password a requirement for notebooks?

### ISSUE THREAD

**Issue by madsroskar** [n1try/mininote#17]
As the contents of the notebooks are stored in a plain .json-file on my computer, what is the point of creating a password for them? And why is it required? 

(If I could add a label, I'd add a question label :D )

**Comment by madsroskar** [comment]
(If I could add a label, I'd add a `question` label :D )

**Comment by n1try** [comment]
Because the `mininote` instance could also be exposed to the internet.

**Comment by madsroskar** [comment]
Obviously. Brain fart on my end. Thanks!
