### ISSUE TITLE
Add frontend unit tests

### ISSUE THREAD

**Issue by n1try** [n1try/mininote#21]

**Comment by nicoleCamoro** [comment]
can I take this?

**Comment by AntonyFenton** [comment]
Hey @nicoleCamoro It's been a couple of days, are you still working on this? Otherwise I would like to have a stab at it!

**Comment by nicoleCamoro** [comment]
Hi @AntonyFenton ! I'm still working on it but I got a bit busy at work. Go have a shot if you want. 😄

**Comment by AntonyFenton** [comment]
Cool, i'll have a pop at it too. Thanks

**Comment by n1try** [comment]
Resolved by #41
