### ISSUE TITLE
Fix styling bugs

### ISSUE THREAD

**Issue by n1try** [n1try/mininote#23]
There are several styling bugs which have not been there in an earlier version. The screenshot show a comparison between a mininote instance hosted on my private server that was installed several months ago and an instance that was installed today. The first screenshot shows the way it should look like, the second one how it currently looks like.

It might be due to version changes in the frontend's dependencies or something else. Please feel free to help me find out and fix this :slightly_smiling_face: 

### Right
![image](https://user-images.githubusercontent.com/8978843/46328894-d1da4180-c5be-11e8-8cf6-a3188ea3608c.png)

### Wrong
![image](https://user-images.githubusercontent.com/8978843/46328903-dd2d6d00-c5be-11e8-8d5a-875c28aa8f8c.png)

### Right
![image](https://user-images.githubusercontent.com/8978843/46328885-c555e900-c5be-11e8-8fa4-4c9d4c8c65ed.png)

### Wrong
![image](https://user-images.githubusercontent.com/8978843/46328867-abb4a180-c5be-11e8-8f45-56bca4474a98.png)

**Comment by paperlambda** [comment]
what browser did you use?

**Comment by paperlambda** [comment]
nevermind, i think i know what are the issues. btw, the first image doesnt quite clear, you want the `alert` to be on top of the `form`?

**Comment by n1try** [comment]
It appears in both Firefox and Chrome. 

Concerning the first screenshot: the alert should overlap the search bar, but instead it shows up above it and shifts the entire page down while it's there (maybe a problem of relative vs. absolute positioning?).

**Comment by paperlambda** [comment]
yeah, that's the case. i figured that you set the position to `fixed` but it got overwritten to `relative`. checking it out right now
