### ISSUE TITLE
An error has occured. Sorry.

### ISSUE THREAD

**Issue by asis-team** [n1try/mininote#4]
After installing, cannot create any new notebook and it keeps showing "An error has occured. Sorry."

**Comment by n1try** [comment]
Can you please provide some more detailed information? It'd be helpful to see the server's log output as well as the body of the faulty request. You can get the latter by using your browser's developer tool's network tab.

**Comment by asis-team** [comment]
Requested URL: http://localhost:3000/api/notebook/test
Method: HEAD
Status Code: 404 Not Found
is there any automatic log generator for it?

**Comment by n1try** [comment]
That 404 shouldn't be a problem as it just indicates the frontend that the `test` notebook hasn't been created, yet. This shouldn't result in an error. Are there any other requests with non-`200` responses? And does the server print any output?

**Comment by asis-team** [comment]
There is no output on the server side, and after entering the password there is: 
NotesApiService.js?3346:15 POST http://localhost:3000/api/notebook 404 (Not Found)
  | create | @ | NotesApiService.js?3346:15
-- | -- | -- | --
  | createNotebook | @ | ControlBar.vue?6038:120
  | boundFn | @ | vue.esm.js?65d7:190
  | invoker | @ | vue.esm.js?65d7:2004
  | fn._withTask.fn._withTask | @ | vue.esm.js?65d7:1802

**Comment by n1try** [comment]
Did the server print out `Listening on localhost:3000.`?

**Comment by asis-team** [comment]
yes:
>Listening at http://localhost:3000
(node:21948) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/home/lisbeth/Documents/mininote/mininote-frontend/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
(node:21948) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21948) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by n1try** [comment]
There we got the problem. The server immediately crashed with code 3. What Node version are you using?

**Comment by asis-team** [comment]
node -v
v8.10.0

**Comment by n1try** [comment]
Alright, I'm not sure, yet, at which point this problem exactly occurs, but it's due to [this deprecation](https://nodejs.org/dist/latest-v8.x/docs/api/deprecations.html#deprecations_dep0018_unhandled_promise_rejections) in Node 8.10. I'm going to create a new issue to fix that. Until then, you probably need to use a Node version < than 8.10, sorry. To use manage multiple versions on the same machine, I can recommend [nvm-windows](https://github.com/coreybutler/nvm-windows).

**Comment by asis-team** [comment]
Thanks
