### ISSUE TITLE
Importing bootstrap.css failed on build

### ISSUE THREAD

**Issue by danielmizrachi** [n1try/mininote#6]
```
ERROR in ./src/main.js
Module not found: Error: Can't resolve 'bootstrap/dist/css/bootstrap.css' in '/home/daniel/node/mininote/mininote-frontend/src'
 @ ./src/main.js 7:0-42
```
`npm run build` in /mininote-frontend generates the error above.

System: Ubuntu LTS
`node -v`: v9.8.0
`npm -v`:  5.6.0

**Comment by n1try** [comment]
Should be fixed now. Please re-check. If not fixed, feel free to open this issue.
