### ISSUE TITLE
Make editor collapsible

### ISSUE THREAD

**Issue by n1try** [n1try/mininote#8]
Make the Markdown editor horizontally collapsible to have a wider rendered view, especially on small screens.

**Comment by lucas-carl** [comment]
Hey @n1try I would love to help you with this #hacktoberfest

**Comment by n1try** [comment]
Yes, go for it :+1:

**Comment by andlehma** [comment]
Solved as of https://github.com/n1try/mininote/commit/a3a35f77e3708ef5cfc6f18b7e62632ac8ca20c9
